name: Convertik
bundleIdPrefix: com.azg
deploymentTarget:
  iOS: 15.0

options:
  bundleIdPrefix: com.azg
  createIntermediateGroups: true
  groupSortPosition: top

configs:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Debug.xcconfig  # Используем Debug для Release по умолчанию
  DeployOld: Configs/DeployOld.xcconfig
  DeployNew: Configs/DeployNew.xcconfig

schemes:
  Convertik:
    build:
      targets:
        Convertik: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  
  Convertik-Old:
    build:
      targets:
        Convertik: all
    run:
      config: DeployOld
    test:
      config: Debug
    profile:
      config: DeployOld
    analyze:
      config: DeployOld
    archive:
      config: DeployOld
  
  Convertik-New:
    build:
      targets:
        Convertik: all
    run:
      config: DeployNew
    test:
      config: Debug
    profile:
      config: DeployNew
    analyze:
      config: DeployNew
    archive:
      config: DeployNew

dependencies:
  - package: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 10.15.0

targets:
  Convertik:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        SWIFT_VERSION: "5.9"
        SWIFT_COMPILATION_MODE: wholemodule
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      configs:
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
        DeployOld:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
        DeployNew:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    sources:
      - path: Convertik
        excludes:
          - "**/*.md"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Конвертик
        CFBundleShortVersionString: "2.4"
        CFBundleVersion: "1"
        LSApplicationCategoryType: "public.app-category.finance"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: "Default Configuration"
                UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen:
          UIColorName: "AccentColor"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        BGTaskSchedulerPermittedIdentifiers:
          - "$(BG_TASK_REFRESH_IDENTIFIER)"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true