name: Convertik
bundleIdPrefix: com.azg
deploymentTarget:
  iOS: 15.0

options:
  bundleIdPrefix: com.azg
  createIntermediateGroups: true
  groupSortPosition: top

schemes:
  Convertik:
    build:
      targets:
        Convertik: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

dependencies:
  - package: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 10.15.0

targets:
  Convertik:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: Convertik
        excludes:
          - "**/*.md"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Конвертик
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSApplicationCategoryType: "public.app-category.finance"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: "Default Configuration"
                UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen:
          UIColorName: "AccentColor"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        BGTaskSchedulerPermittedIdentifiers:
          - "com.azg.convertik.refresh"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true