"""Initial migration: create tables

Revision ID: 633031fc1430
Revises: 
Create Date: 2025-07-31 17:53:14.628697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '633031fc1430'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iap_receipts',
    sa.Column('original_tx_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('original_tx_id')
    )
    op.create_index(op.f('ix_iap_receipts_device_id'), 'iap_receipts', ['device_id'], unique=False)
    op.create_table('push_tokens',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_code'), 'rates', ['code'], unique=True)
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_device_id'), 'usage_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_usage_events_event_name'), 'usage_events', ['event_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_event_name'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_device_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_rates_code'), table_name='rates')
    op.drop_table('rates')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_iap_receipts_device_id'), table_name='iap_receipts')
    op.drop_table('iap_receipts')
    # ### end Alembic commands ###
